In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [0]:
word=["hey this is abishek","hey this is akash","how are you","i am good abishek"]

In [0]:
tokenizer = Tokenizer(num_words=100, split=" ")
tokenizer.fit_on_texts(word)

In [0]:
X = tokenizer.texts_to_sequences(word)
X1 = pad_sequences(X) # padding our text vector so they all have the same length

In [0]:
X

[[1, 2, 3, 4], [1, 2, 3, 5], [6, 7, 8], [9, 10, 11, 4]]

In [0]:
X1

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  5],
       [ 0,  6,  7,  8],
       [ 9, 10, 11,  4]], dtype=int32)

In [0]:
type(X)

list

In [0]:
type(X1)

numpy.ndarray

In [0]:
X1.shape[1]

4

In [0]:
import tflearn

Instructions for updating:
Colocations handled automatically by placer.


tflearn 
the padding is done explicitly

In [0]:
#set max sentence length
max_sent_length = 10
#make vocab processor
vocab_processor = tflearn.data_utils.VocabularyProcessor(max_sent_length)
# our sentences represented as indices instead of words
data = list(vocab_processor.fit_transform(word))

Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.


In [0]:
data




[array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0]),
 array([1, 2, 3, 5, 0, 0, 0, 0, 0, 0]),
 array([6, 7, 8, 0, 0, 0, 0, 0, 0, 0]),
 array([ 9, 10, 11,  4,  0,  0,  0,  0,  0,  0])]

In [0]:
import numpy 
data1=numpy.asarray(data)

In [0]:
data1.shape[1]

10

In [0]:
X1

array([[1, 2, 3, 4],
       [1, 2, 3, 5],
       [0, 6, 7, 8],
       [0, 0, 9, 4]], dtype=int32)

In [0]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
#vocab_size = 50
#encoded_docs = [one_hot(d, vocab_size) for d in docs]
#print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
#padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
#print(padded_docs)
tokenizer = Tokenizer(num_words=50, split=" ")
tokenizer.fit_on_texts(docs)
X = tokenizer.texts_to_sequences(docs)
padded_docs= pad_sequences(X) 


# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_4 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 89.999998


In [0]:
predictions = model.predict(out)

In [0]:
predictions

array([[0.5172884 ],
       [0.45782447],
       [0.51611716]], dtype=float32)

In [0]:
predictions[0]

array([0.5172884], dtype=float32)

In [0]:
padded_docs

array([[ 0,  0,  6,  2],
       [ 0,  0,  3,  1],
       [ 0,  0,  7,  4],
       [ 0,  0,  8,  1],
       [ 0,  0,  0,  9],
       [ 0,  0,  0, 10],
       [ 0,  0,  5,  4],
       [ 0,  0, 11,  3],
       [ 0,  0,  5,  1],
       [12, 13,  2, 14]], dtype=int32)

In [0]:

vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
#pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[13, 28], [16, 28], [25, 36], [18, 28], [15], [24], [12, 36], [5, 16], [12, 28], [4, 18, 28, 11]]
[[13 28  0  0]
 [16 28  0  0]
 [25 36  0  0]
 [18 28  0  0]
 [15  0  0  0]
 [24  0  0  0]
 [12 36  0  0]
 [ 5 16  0  0]
 [12 28  0  0]
 [ 4 18 28 11]]


In [0]:
X_test=['Great work','Good effort well done','poor']

In [0]:
tokenizer = Tokenizer(num_words=50, split=" ")
tokenizer.fit_on_texts(X_test)
X_test = tokenizer.texts_to_sequences(X_test)
out= pad_sequences(X_test) 

In [0]:
out

array([[0, 0, 1, 2],
       [3, 4, 5, 6],
       [0, 0, 0, 7]], dtype=int32)

In [0]:
numpy.argmax([0.5,1.5,8])

2